set style line 1 lt 1    lc rgb "blue" lw 5 
set style line 2 lt 2 dt 2 lc rgb "red"  lw 5 
set style line 3 lt 3 dt 3 lc rgb "blue" lw 5 
set style line 4 lt 4 dt 4 lc rgb "red"  lw 3 
set style line 5 lt 5 dt 5 lc rgb "black" lw 3 
set style line 6 lt 6 dt 6 lc rgb "red" lw 3 
set style line 7 lt 7 dt 7 lc rgb "blue" lw 3 
set style line 8 lt 8 dt 8 lc rgb "blue" lw 3 

#used in the rw_timeline plot
set style line 101 lt 1  lc rgb "blue"  lw 5 pt 1 ps 2
set style line 102 lt 1  lc rgb "red"   lw 5 pt 2 ps 2
set style line 103 lt 1  lc rgb "black" lw 5 pt 3 ps 2


set style line 1001 lt 1  lc rgb "blue"  lw 5 pt 1 ps 2
set style line 1002 lt 1  lc rgb "red"   lw 5 pt 2 ps 2
set style line 1003 lt 1  lc rgb "black"  lw 1 pt 3 ps 1

set style line 300  linewidth 1.000 pointtype 2 dashtype 1 pointsize default pointinterval 0
